CREATE TABLE [dbo].[dim_TRMS_TrainModelSettings] (
    [TRMS_ID]               INT            IDENTITY (1, 1) NOT NULL,
    [TRMS_PES_ID]           INT            NOT NULL,
    [TRMS_MLA_ID]           INT            NOT NULL,
    [TRMS_JSONParams]       NVARCHAR (MAX) NULL,
    [TRMS_Active]           TINYINT        NOT NULL,
    [TRMS_Test_R2_1]        FLOAT (53)     NULL,
    [TRMS_Test_RMSE_1]      FLOAT (53)     NULL,
    [TRMS_Test_R2_2]        FLOAT (53)     NULL,
    [TRMS_Test_RMSE_2]      FLOAT (53)     NULL,
    [TRMS_Test_RMSE]        FLOAT (53)     NULL,
    [TRMS_Test_R2]          FLOAT (53)     NULL,
    [TRMS_Train_R2_1]       FLOAT (53)     NULL,
    [TRMS_Train_RMSE_1]     FLOAT (53)     NULL,
    [TRMS_Train_R2_2]       FLOAT (53)     NULL,
    [TRMS_Train_RMSE_2]     FLOAT (53)     NULL,
    [TRMS_Train_RMSE]       FLOAT (53)     NULL,
    [TRMS_Train_R2]         FLOAT (53)     NULL,
    [TRMS_Target_1]         NVARCHAR (50)  NULL,
    [TRMS_Target_2]         NVARCHAR (50)  NULL,
    [TRMS_N_Executions]     INT            DEFAULT ((0)) NOT NULL,
    [TRMS_AVG_Test_R2_1]    FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Test_RMSE_1]  FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Test_R2_2]    FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Test_RMSE_2]  FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Test_RMSE]    FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Test_R2]      FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Train_R2_1]   FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Train_RMSE_1] FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Train_R2_2]   FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Train_RMSE_2] FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Train_RMSE]   FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    [TRMS_AVG_Train_R2]     FLOAT (53)     DEFAULT ((0.0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([TRMS_ID] ASC)
);

